### ISSUE TITLE
您好，请问您 多租户事务这块您是如何处理的

### ISSUE THREAD

**Issue by Tomones** [lanyuanxiaoyao/multi-tenant#1]
本地跑起来您的代码进行增删改操作，抛异常javax.persistence.TransactionRequiredException: no transaction is in progress

**Comment by lanyuanxiaoyao** [comment]
@Tomones 这个项目已经过去太久了，我已经不记得细节了，可能是因为 Hibernate 或者 Spring boot 的版本升级以后相关的 API 变化导致的。

**Comment by Tomones** [comment]
@lanyuanxiaoyao 好哇，放弃了，Hibernate多租户 还是有不少坑呢

**Comment by JackPuSteven** [comment]
@lanyuanxiaoyao 你好，请问你有mybatis的实现版本吗，我看到很多人都使用mycat进行分库处理的，感觉有点复杂

**Comment by lanyuanxiaoyao** [comment]
> @lanyuanxiaoyao 你好，请问你有mybatis的实现版本吗，我看到很多人都使用mycat进行分库处理的，感觉有点复杂

mybatis 只是个"工具类", 本身不提供多租户这类实现方案, 所以才会使用 mycat 这类外部组件, 如果不用 mycat 的话, 那大概也就是拦截 sql 语句然后直接改动 sql 加入租户信息来做了

**Comment by JackPuSteven** [comment]
很感谢您的回答！！我想再请问：mybatis拦截sql加入租户信息做成多租户的方式加入到微服务开发当中可行性和稳定性可以接受吗？
