### ISSUE TITLE
volatile 

### ISSUE THREAD

**Issue by victory-wu** [lanyuanxiaoyao/multi-tenant#2]
为什么需要用到volatile，我发现程序用静态变量在这里交叉请求的时候会出现BUG

**Comment by lanyuanxiaoyao** [comment]
> 为什么需要用到volatile，我发现程序用静态变量在这里交叉请求的时候会出现BUG

只是一个简单的示例罢了, 生产环境不会简单地用一个变量来解决 id 的, 所以不用纠结这个问题
